# Generated by Django 5.0.7 on 2024-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_formsubmission_delete_popupform"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("board", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="FormSubmission",
        ),
    ]
