# Generated by Django 5.0.7 on 2024-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_tutorrequest_delete_formsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorrequest",
            name="board",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tutorrequest",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
