# Generated by Django 5.0.7 on 2024-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_tutorrequest_board_alter_tutorrequest_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorrequest",
            name="board",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tutorrequest",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
