# Generated by Django 5.0.7 on 2024-08-03 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_tutorrequest_board_alter_tutorrequest_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tutorrequest",
            name="grade",
            field=models.CharField(max_length=10),
        ),
    ]
